name: Build and publish
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - uses: "cachix/install-nix-action@v22"
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix build
      - run: nix flake check
      - uses: "actions/upload-artifact@v4"
        with:
          name: cv
          path: result/*.pdf

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cv
          path: artifacts
      - uses: ncipollo/release-action@v1.13.0
        with:
          name: ${{ github.ref_name }}
          artifacts: artifacts/*.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
